apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: personal-cert
spec:
  domains:
    - aviralmansingka.me
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: family-cert
spec:
  domains:
    - mansingka.org
